/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
	google?: {
		type?: string;
		project_id?: string;
		private_key_id?: string;
		private_key?: string;
		client_email?: string;
		client_id?: string;
		auth_uri?: string;
		token_uri?: string;
		auth_provider_x509_cert_url?: string;
		client_x509_cert_url?: string;
		universe_domain?: string;
		[k: string]: unknown;
	};
}
