/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A representation of some or all of the games to be played in a season's schedule
 */
export type Schedule = {
	opponent: string;
	date: string;
}[];
