name: deploy

on:
    push:
        branches: ["main"]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.actor }}/de-wdg-broadcast:latest

jobs:
    build:
        name: Build bundle
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ['18.7.0', '18.19.1']

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js v${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}

            - name: Build
              run: |
                npm ci
                npm run build
                npm i --omit=dev

    publish:
        needs: build
        name: Publish Docker image
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Login
              run: |
                echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Build and Publish
              run: |
                docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    deploy:
        needs: publish
        name: Deploy Docker image
        runs-on: ubuntu-latest

        steps:
            # - name: Install SSH key
            #   uses: shimataro/ssh-key-action@v2
            #   with:
            #     key: ${{ secrets.SSH_PRIVATE_KEY }}
            
            - name: SSH Remote Commands
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    cd ${{ secrets.WORK_DIR }}
                    docker-compose pull
                    docker-compose up -d